//Require Express package
const express = require("express");

//Require mogoose for mongoDB
const mongoose = require("mongoose");

//Require User model 
const User  = require("./models/users");
const Movie = require("./models/movies");





//To add record (row) to the database
/*
    //The following lines should be inside a app.get()
    //Create a new instance of User
    const user = new User 
    (
        {
            id : 1,
            username : ahmed,
            password : test
        }
    );

    //Send the instance to the DB
    user.save()
    .then((result)=>
    {
        console.log("Instance added");
    })
    .catch((err)=>
    {
        console.log(err);
    });
*/

//To get a record (row) from the DB
/*
    //The following lines should be inside a app.get()
    User.find()         --> Return all the records (rows)
    .then((result)=>
    {
        console.log(result);
    })
    .catch((err)=>
    {
        console.log(err);
    });

    User.findById("id")     --> Return a record with __id = id.Note: this ID is auto generated by mongoDB. It is bot "id" in the schema)
    .then((result)=>
    {
        console.log(result);
    })
    .catch((err)=>
    {
        console.log(err);
    });
    

*/


//Create a server from Express
const app = express();


//Port number to listen to
const port = process.env.PORT || 5000;


//Connect to mongoDB
const dbURI = 'mongodb+srv://cinema:star123@cluster0.l3vsk.mongodb.net/cinema?retryWrites=true&w=majority';
mongoose.connect(dbURI, { useNewUrlParser: true, useUnifiedTopology: true })
.then(  (result) => 
{
    //If connected successfully, listen to the port
    console.log("Connected to DB");
    app.listen(port, (req,res)=>
    {
        console.log(`Listening to port ${port}`);
    })
})
.catch( (err)    => console.log("ERROR ", err)      );


app.get("/addUser",(req,res)=>
{
    res.sendFile("./form.html",{root : __dirname});
});

app.get("/sUser",(req,res)=>
{

    
    //Send the instance to the DB
    User.find()
    .then((result)=>
    {
        console.log("Search done", result);
        res.send(result);
    })
    .catch((err)=>
    {
        console.log(err);
    });
});

app.use(express.urlencoded({ extended: true }));

app.post("/user",(req,res)=>
{
    const user = new User(req.body);
    //console.log(req.body);
    //console.log(user);

    user.save()
    .then((result)=>
    {
        console.log("Added");
        res.redirect("/sUser");
    })
    .catch((err)=>
    {
        console.log(err);
    });

   

});
